from random import choice
#Enter problems
problems = [
'https://leetcode.com/problems/two-sum',
'https://leetcode.com/problems/number-of-islands',
'https://leetcode.com/problems/reorder-data-in-log-files',
'https://leetcode.com/problems/add-two-numbers',
'https://leetcode.com/problems/maximum-subarray',
'https://leetcode.com/problems/longest-substring-without-repeating-characters',
'https://leetcode.com/problems/merge-two-sorted-lists',
'https://leetcode.com/problems/valid-parentheses',
'https://leetcode.com/problems/product-of-array-except-self',
'https://leetcode.com/problems/product-of-array-except-self',
'https://leetcode.com/problems/best-time-to-buy-and-sell-stock',
'https://leetcode.com/problems/verifying-an-alien-dictionary',
'https://leetcode.com/problems/3sum',
'https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses',
'https://leetcode.com/problems/reverse-linked-list',
'https://leetcode.com/problems/add-strings',
'https://leetcode.com/problems/merge-sorted-array',
'https://leetcode.com/problems/search-in-rotated-sorted-array',
'https://leetcode.com/problems/reverse-integer',
'https://leetcode.com/problems/valid-palindrome-ii',
'https://leetcode.com/problems/roman-to-integer',
'https://leetcode.com/problems/design-hashmap',
'https://leetcode.com/problems/second-highest-salary',
'https://leetcode.com/problems/fizz-buzz',
'https://leetcode.com/problems/subdomain-visit-count',
'https://leetcode.com/problems/diameter-of-binary-tree',
'https://leetcode.com/problems/happy-number',
'https://leetcode.com/problems/move-zeroes',
'https://leetcode.com/problems/most-common-word',
'https://leetcode.com/problems/min-stack',
'https://leetcode.com/problems/palindrome-number',
'https://leetcode.com/problems/first-unique-character-in-a-string',
'https://leetcode.com/problems/single-number',
'https://leetcode.com/problems/longest-common-prefix',
'https://leetcode.com/problems/add-and-search-word-data-structure-design',
'https://leetcode.com/problems/valid-palindrome',
'https://leetcode.com/problems/maximum-product-subarray',
'https://leetcode.com/problems/string-compression',
'https://leetcode.com/problems/combine-two-tables',
'https://leetcode.com/problems/sort-colors',
'https://leetcode.com/problems/count-primes',
'https://leetcode.com/problems/logger-rate-limiter',
'https://leetcode.com/problems/first-bad-version',
'https://leetcode.com/problems/range-sum-of-bst',
'https://leetcode.com/problems/missing-number',
'https://leetcode.com/problems/valid-anagram',
'https://leetcode.com/problems/reverse-string',
'https://leetcode.com/problems/two-sum-ii-input-array-is-sorted',
'https://leetcode.com/problems/count-and-say',
'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii',
'https://leetcode.com/problems/climbing-stairs',
'https://leetcode.com/problems/symmetric-tree',
'https://leetcode.com/problems/shuffle-an-array',
'https://leetcode.com/problems/add-binary',
'https://leetcode.com/problems/multiply-strings',
'https://leetcode.com/problems/majority-element',
'https://leetcode.com/problems/maximum-depth-of-binary-tree',
'https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree',
'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array',
'https://leetcode.com/problems/middle-of-the-linked-list',
'https://leetcode.com/problems/invert-binary-tree',
'https://leetcode.com/problems/linked-list-cycle',
'https://leetcode.com/problems/squares-of-a-sorted-array',
'https://leetcode.com/problems/sum-of-two-integers',
'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii',
'https://leetcode.com/problems/repeated-substring-pattern',
'https://leetcode.com/problems/longest-repeating-character-replacement',
'https://leetcode.com/problems/merge-two-binary-trees',
'https://leetcode.com/problems/monotonic-array',
'https://leetcode.com/problems/divisor-game',
'https://leetcode.com/problems/number-of-1-bits',
'https://leetcode.com/problems/balanced-binary-tree',
'https://leetcode.com/problems/unique-email-addresses',
'https://leetcode.com/problems/find-all-duplicates-in-an-array',
'https://leetcode.com/problems/isomorphic-strings'
]
sequence = [i for i in range(len(problems))]
choices = []
#Enter number of problems to do
while len(choices) < 3:
  problem_choice = choice(sequence)
  if problem_choice not in choices:
   choices.append(problem_choice)
for choice in choices:
  print(problems[choice])
print(len(problems), ' to go!')