# Generated by Django 3.0.2 on 2020-09-21 18:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200921_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='additional_notes',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
