# Generated by Django 3.0.2 on 2020-09-17 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200411_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='explanation',
            field=ckeditor.fields.RichTextField(default='hi'),
            preserve_default=False,
        ),
    ]
