# Generated by Django 3.0.2 on 2020-09-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200917_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.TextField(choices=[('1', 'Arrays'), ('2', 'Strings'), ('3', 'Linked Lists'), ('3', 'Trees'), ('3', 'Graphs')], default='1'),
        ),
        migrations.AddField(
            model_name='post',
            name='difficulty',
            field=models.TextField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default='1'),
        ),
    ]
