# Generated by Django 3.0.2 on 2020-09-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200917_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alt_category',
            field=models.TextField(choices=[('arrays', 'Arrays'), ('strings', 'Strings'), ('linked lists', 'Linked Lists'), ('trees', 'Trees'), ('graphs', 'Graphs')], null=True),
        ),
    ]
